server:
  port: 8081
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: flight_route
            uri: lb://flight
            predicates:
              - Path=/flight
          - id: booking
            uri: lb://booking
            predicates:
              -  Path=/booking
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka